version: '3.7'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db  
         
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: imagedb
    ports:
      - 5432:5432

  sut:
    build: .
    command: ./run_tests.sh
    depends_on: 
      - db
      - app
